site_name: "C4G BLIS Documentations"

markdown_extensions:
  - abbr
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - git-revision-date
  - search

edit_uri: edit/main/docs/
repo_url: https://github.com/leemingee/BLIS

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - search.suggest

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
